### ISSUE TITLE
LightAPI 2.0.2

### ISSUE THREAD

**Issue by hexosse** [BeYkeRYkt/LightAPI#1]
Hello BeYkeRYkt,

When do you plan to release LightAPI 2.0.2 ?

Thanks.

**Comment by rErEaT** [comment]
I am waiting for that!

**Comment by Androkai** [comment]
Where are problems in combination with ShinyItems. Using booth together makes entities disappear then entering a cave or holding a torch at night. Not sure where the problem is located by, LightAPI or ShinyItems. Tested with Spigot 1.9.4, LightAPI 2.0.2 (self-compiled from source) and ShinyItems 1.5.3

**Comment by rErEaT** [comment]
1.10 is here
